### PR TITLE
My name is nicola too haha

### PR DESCRIPTION
**Pull request by 117**
Lol! I was looking for github usernames and typed urs out. We have a lot of the same interests :P nice name

### CODE REVIEW

**Comment by 117** [comment]
did you draw your pfp? its really good 👀

**Comment by 117** [comment]
Capture 2022-04-07 at 09 59 20
if u wanna share drawings n shit add me on disc 💕

**Comment by aqilc** [comment]
omg

**Comment by aqilc** [comment]
can i please get in on the discord sharing? mines @aqilc

**Comment by aqilc** [comment]
@nicxla @117 hope u guys have a great weekend

**Pull request closed without merging**
